### ISSUE TITLE
Improve config handling

### ISSUE THREAD

**Issue by mietek** [mietek/gitit#4]
Currently, the [`.profile.d/gitit.sh`](https://github.com/mietek/gitit/blob/master/.profile.d/gitit.sh) script handles config on Heroku.  Nothing is done to handle config when the app is deployed elsewhere.

**Comment by Edenharder** [comment]
I deploy gitit on Heroku, but there is something wrong:

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
